aliases: &install-deps
  run:
    name: Install dependencies
    command: apt-get update -y && apt-get install libyaml-cpp-dev libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3-dev libzip-dev git -y

version: 3
jobs:
  teststyle:
    docker:
      - image: debian:stretch-backports
    steps:
      - checkout
      - run:
          name: Install preliminary dependencies
          command: apt-get update -y && apt-get install curl gnupg apt-transport-https -y
      - run:
          name: Add clang 8.0 to apt sources
          command: echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-8 main" >> /etc/apt/sources.list
      - run:
          name: Add LLVM apt key
          command: curl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
      - run:
          name: Install dependencies
          command: apt-get update -y && apt-get install git clang-format-8 -y
      - run:
          name: Style checker
          command: bash scripts/stylecheck.sh
  build:
    docker:
      - image: debian:stretch-backports
    steps:
      - checkout
      - *install-deps
      - run:
          name: Check version
          command: python3 check_version.py
      - run:
          name: Build
          command: make -j2
  build-python:
    docker:
      - image: debian:stretch-backports
    steps:
      - checkout
      - *install-deps
      - run:
          name: Build python module
          command: make -j2 build/horizon.so
      - run:
          name: Test python module
          command: python3 -c 'import sys; sys.path.append("build"); import horizon'

workflows:
  version: 2
  test-and-build:
    jobs:
      - teststyle
      - build
      - build-python
